title: Azure Landing Zone for Startups
description: Opinionated, deployable Azure Landing Zone for digital-native companies and startups. Bicep + Terraform.
theme: null
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: light
search_enabled: true

# Optional, but nice for project pages
aux_links:
  "GitHub Repo":
    - "https://github.com/ricmmartins/azure-landing-zone-startups"

# Make relative links behave well in project pages
# If you later map a custom domain, you can remove baseurl.
baseurl: ""
url: "https://azurelanding.zone"

# Just the Docs settings
heading_anchors: true

# If you want nicer nav behavior
nav_sort: case_sensitive
